//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string aboutMe {
            get {
                return ResourceManager.GetString("aboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seoul, Korea.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Level.
        /// </summary>
        public static string businessLevel {
            get {
                return ResourceManager.GetString("businessLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string company1 {
            get {
                return ResourceManager.GetString("company1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string company2 {
            get {
                return ResourceManager.GetString("company2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string company3 {
            get {
                return ResourceManager.GetString("company3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string company4 {
            get {
                return ResourceManager.GetString("company4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download CV.
        /// </summary>
        public static string downloadCV {
            get {
                return ResourceManager.GetString("downloadCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string education {
            get {
                return ResourceManager.GetString("education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobDesc1.
        /// </summary>
        public static string jobDesc1 {
            get {
                return ResourceManager.GetString("jobDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobDesc2.
        /// </summary>
        public static string jobDesc2 {
            get {
                return ResourceManager.GetString("jobDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobDesc3.
        /// </summary>
        public static string jobDesc3 {
            get {
                return ResourceManager.GetString("jobDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobDesc4.
        /// </summary>
        public static string jobDesc4 {
            get {
                return ResourceManager.GetString("jobDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string jobTitle1 {
            get {
                return ResourceManager.GetString("jobTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string jobTitle2 {
            get {
                return ResourceManager.GetString("jobTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string jobTitle3 {
            get {
                return ResourceManager.GetString("jobTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string jobTitle4 {
            get {
                return ResourceManager.GetString("jobTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        public static string korean {
            get {
                return ResourceManager.GetString("korean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Blog Posts.
        /// </summary>
        public static string latestBlogPosts {
            get {
                return ResourceManager.GetString("latestBlogPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Engineering.
        /// </summary>
        public static string major1 {
            get {
                return ResourceManager.GetString("major1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor of Information Technology.
        /// </summary>
        public static string major2 {
            get {
                return ResourceManager.GetString("major2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Hobby.
        /// </summary>
        public static string myHobby {
            get {
                return ResourceManager.GetString("myHobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi? My name is Jinsu Kim working as a web developer for Bodog (http://www.bodog.eu/). I develop the business back office for online games..
        /// </summary>
        public static string myIntroduction {
            get {
                return ResourceManager.GetString("myIntroduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jinsu Kim.
        /// </summary>
        public static string myName {
            get {
                return ResourceManager.GetString("myName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native Language.
        /// </summary>
        public static string nativeLanguage {
            get {
                return ResourceManager.GetString("nativeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectDesc1.
        /// </summary>
        public static string projectDesc1 {
            get {
                return ResourceManager.GetString("projectDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectDesc2.
        /// </summary>
        public static string projectDesc2 {
            get {
                return ResourceManager.GetString("projectDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectDesc3.
        /// </summary>
        public static string projectDesc3 {
            get {
                return ResourceManager.GetString("projectDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projectDesc4.
        /// </summary>
        public static string projectDesc4 {
            get {
                return ResourceManager.GetString("projectDesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Project.
        /// </summary>
        public static string recentProject {
            get {
                return ResourceManager.GetString("recentProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string skills {
            get {
                return ResourceManager.GetString("skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills Intro.
        /// </summary>
        public static string skillsIntro {
            get {
                return ResourceManager.GetString("skillsIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inha University.
        /// </summary>
        public static string university1 {
            get {
                return ResourceManager.GetString("university1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University of Delhi.
        /// </summary>
        public static string university2 {
            get {
                return ResourceManager.GetString("university2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Experiences.
        /// </summary>
        public static string workExperience {
            get {
                return ResourceManager.GetString("workExperience", resourceCulture);
            }
        }
    }
}
